//
//  g_nvid_string.c
//  NVMac
//
//  Created by Spotlight Deveaux on 2025-06-03.
//

#include <stdio.h>

// TODO(spotlightishere): This should probably match the actual version
// and be generated by a shell script instead of being hardcoded.
const char  NVRM_ID[] = "nvidia id: NVIDIA UNIX Open Kernel Module for x86_64  575.57.08  Release Build  (root@Mac-mini.local)  Thu Jan  1 00:00:00 UTC 1970";
const char *const pNVRM_ID =  NVRM_ID + 11;
